ARG TAG_VERSION=":latest"
ARG BASE_IMAGE="sambuc/renku-shell${TAG_VERSION}-zsh"
FROM ${BASE_IMAGE}

SHELL ["/bin/sh", "-c"]
USER root

RUN apk add --no-cache make clang20

# Setup zsh env
ARG CASTLE_PATH="/home/renku/castle"
COPY castle ${CASTLE_PATH}
RUN chown -R renku:renku ${CASTLE_PATH}

USER renku
RUN \
	cd ${CASTLE_PATH} && \
	make tmux vim omz zsh

