ARG TAG_VERSION=":latest"
ARG BASE_IMAGE="sambuc/renku-xpra${TAG_VERSION}"
FROM ${BASE_IMAGE}

SHELL ["/bin/sh", "-c"]

USER root

RUN \
	apt-get install -y --no-install-recommends xfce4 xfce4-goodies

USER ubuntu

CMD xpra seamless \
	--daemon=no \
	--mdns=no \
	--http=yes \
	--systemd-run=no \
	--webcam=no \
	--no-audio \
	--printing=no \
	--clipboard=yes \
	--clipboard-direction=both \
	--exit-with-children=no \
	--bind-tcp="0.0.0.0:${RENKU_SESSION_PORT:-8888}"

